### ISSUE TITLE
Formz UI

### ISSUE THREAD

**Issue by fedir** [romm/formz#62]
Hey Romain,
First of all, thank You very much for Your great work.
I've a question about Formz project :
If any UI exists for TYPO3 Backend (as form builder part of Powermail for example), so the web-master could create/modify it's forms parameters in the TYPO3 Backend ot create complex multi-step form with the choice of field validation ?
Or this extension is designed only for TYPO3 Developers ?
Thank You for Your answer,
Best regards,
Fedir

**Comment by romm** [comment]
Hi @fedir, thank you for your kind words. :)

The answer is pretty simple: no there is no UI for this kind of complex configuration, and there will probably never be. There are several reasons why I chose not to go in this direction:

- FormZ is really powerful. And it will be even more in a few months with a new feature I'm currently working on for my customer. Transforming all these features in an understandable and powerful UI is a HUGE work, probably even more than what it took to build the current PHP core API.
- I don't have time for this kind of project. For now, I've been working on my own without external help, and I doubt anyone would want/accept to help me for this kind of task, and mostly because: (see above)
- The TYPO3 v8 core extension (EXT:form) does provide this functionality, and it works just really (**really**) well. This would be a huge waste of time trying to build something that already exists.

Still, I do believe the direction I'm taking for FormZ (since the core extension remake announcement) makes perfect sense. I mostly want FormZ to provide features that will help building huge/complex forms, and these kind of forms do not need a built-in UI interface (I will try to write an article explaining why I believe this).

To answer your question: **no**, FormZ is not designed **only** for developers. It also provides a powerful Fluid API, as well as strong CSS helpers, that help integrators doing their job with fewer efforts. See [integrator documentation](https://docs.typo3.org/typo3cms/extensions/formz/1.0.0/06-IntegratorManual/) for more information.
